### PR TITLE
update ch 25

### PR DESCRIPTION
**Pull request by lgibson7**

### CODE REVIEW

**Review by Ken-Vu — CHANGES_REQUESTED** [review]
Take care to remove warnings when running code chunks.  You can suppress them (especially when you load in the needed packages in the **Prerequisites** section) by going into the code chunk and adding the argument _warning=FALSE_ where the {} is

**Comment by lgibson7** [comment]
I didn't have any errors when I run my code chunks. Can you show me the error?

**Comment by Ken-Vu** [comment]
@lgibson7 To clarify, it's not an error, but a warning message when loading the libraries that I felt looked out of place in the Learning Objectives section.  
image

**Comment by Ken-Vu** [comment]
You can turn off warnings by going to the top of the code chunk (see picture below circled in red) and adding the argument 
`warning=FALSE`.

So the code chunk would look like this:
image

**Comment by lgibson7** [comment]
@Ken-Vu I don't receive that error message when I render. I imagine the `suppressPackageStartupMessages()` function should stop all messages and warnings from populating. It might be something with your system. In any case, I've added `warning = FALSE` to the chunk options. 
Screenshot 2024-04-01 at 4 46 11 PM

**Review by Ken-Vu — APPROVED** [review]
Looks good.

**Comment by Ken-Vu** [comment]
Possibly.  Not sure if it will show up in bookdown so it could be good to add warning suppression as a precaution.

**Pull request merged**
