### PR TITLE
Chapter 18 content

### PR DESCRIPTION
**Pull request by JauntyJJS**
Added content for Chapter 18. 

Used R package reactable and reactablefmtr to see view tibble changes in section "Implicit missing values" when [tidyr::complete()](https://tidyr.tidyverse.org/reference/complete.html) was used. This changes are not displayed in the book and can be hard to understand.

### CODE REVIEW

**Review by Ken-Vu — CHANGES_REQUESTED** [review]
Hi Jeremy, for the first slides in the chapter, can you format the first page (the section labelled Introduction) to match the first page of other chapters?  The rest of the other chapters begin with a list of learning objectives (see Ch 15 as an example) so it would help the reader follow along more easily if they all have similar formatting as well as get an idea of what to expect reading the chapter.

If anything, you can move the introduction section to its own section or add the content to other existing sections for Ch 18.

**Comment by JauntyJJS** [comment]
Hi Ken,

I have made the first slide to have just the learning objective and move the Introduction as a new section.

**Comment by Ken-Vu** [comment]
Looks good.  Thank you!

**Review by Ken-Vu — APPROVED** [review]

**Review by Ken-Vu — APPROVED** [review]
Looks good.  Thanks, Jeremy

**Pull request merged**
